name: funds_tracker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


#---------------- PACKAGES -------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  google_fonts: ^6.1.0
  flutter_svg: ^0.23.0+1
  flutter_native_splash: ^2.2.0+1

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management


#------------------- PACKAGES END ----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  fontify: ^0.3.0-nullsafety.1
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

fontify:
    input_svg_dir: "assets/icons/"
    output_font_file: "assets/fonts/my_icons_font.otf"

    output_class_file: "lib/src/my_icons.dart"
    class_name: "MyIcons"
    indent: 4
    package: my_font_package

    font_name: "MyIcons"
    normalize: true
    ignore_shapes: true

    recursive: true
    verbose: false

  
assets:
    - assets/images/
    - assets/icons/
    - lib/images/
  

  
  

  
  

  
  
  
  
  

fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Thin.ttf
          style: italic

    - family: MyIcons
      fonts:
        - asset: fonts/my_icons_font.otf

      
      
    
    
    
  
  
  
