name: funds_tracker
description: This is an app that will elp ACLIS board to track their expenses 
  and how their funds are being used.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


#---------------- PACKAGES -------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.6

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6

  #Other packages
  date_field: ^6.0.0
  dropdown_button2: ^2.3.9
  badges: ^3.1.2
  awesome_dialog: ^3.1.0
  fl_chart: ^0.70.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.2.2
  firebase_database: ^11.3.1
  provider: ^6.1.1
  json_annotation: ^4.8.0
  intl: ^0.20.2
  flutter_logger: ^1.1.8

#------------------- PACKAGES END ----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1




flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ---------------#
  assets:
      - assets/images/
      - assets/icons/

  #--------------- LOCAL FONTS ---------------#
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Thin.ttf
        - asset: assets/fonts/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-Black.ttf

